import Head from 'next/head'
import HomeSubheader from '../components/HomeSubheader'
import BrandLogos from '../components/BrandLogos'
import HomeCards from '../components/HomeCards'
import Loader from "../components/Loader"
import sanityClient from '../src/client'
import ContactModal from '../components/ContactModal'
import { handleContactClick } from '../public/utils'

export default function Home({headlineText, brandLogos, homeCardData}) {

  return (
    <div className="page-container">
      <Head>
        <title>C.M. Miller Content Writer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/curtis_miller_logo.png" />
      </Head>
      <div className="content-wrapper">
        <div className="home-headerWrapper">
          <div className="home-headerTextContainer">
            <h1 className="home-title">
              C. M. Miller
            </h1>
            <p className="home-subtitle">
              Award-Winning Writer
            </p>
          </div>
        </div>
        {!headlineText
          ?
          <Loader />
          :
          headlineText.map((data) => {
            return (
              <HomeSubheader key={data._id} subheaderText={data.headline} />
            )
          })
        }
        <BrandLogos
          brandLogos={brandLogos}
        />
        <HomeCards
          homeCardData={homeCardData}
        />
        <div className="putMeToWorkContainer">
          <span className="putMeToWorkButton" onClick={handleContactClick}>Put Me To Work</span>
        </div>
      </div>
      <ContactModal/>
    </div>
  )
}

export const getServerSideProps = async () => {

  const headlineText = await sanityClient.fetch(`*[_type == "headlineText"] {
    _id,
    headline
  }`)

   const brandLogos = await sanityClient.fetch(`*[_type == "brandlogos"] | order(order) {
    _id,
    clientType,
    title,
    link,
    "imageUrl": image.asset->url,
    order
  }`)

  const homeCardData = await sanityClient.fetch(`*[_type == "homecards"] | order(_createdAt) {
    _id,
    "iconURL": hc_icon.asset->url,
    hc_header,
    hc_content,
    hc_button_text,
    hc_button_link
  }`)

  return {
    props: {
      headlineText,
      brandLogos,
      homeCardData
    }
  }
}
